### ISSUE TITLE
Node-red project support

### ISSUE THREAD

**Issue by scox-antillion** [barshociaj/node-red-contrib-js-storage#2]
I was trying to get this working in project mode. It seems this currently doesn't support project (from the error logs).
Can we get support for projects?

**Comment by barshociaj** [comment]
That's right, projects are not supported. It would be much more difficult to adapt and maintain and I can't afford it at this time, sorry. As an alternative consider raising the request with the Node-RED team (this would solve the long-term maintenance problem).

**Comment by beasteers** [comment]
Hmmm unfortunately, I see what you mean 😓 I thought that applying to the projects feature would just be tracking from a different directory, but it looks like [it's quite intertwined](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/runtime/lib/storage/localfilesystem/projects/index.js) in their built in storage module. 

It's such a shame considering HOW much the projects feature would benefit from this storage module. Like I don't get why the projects feature exists without this (\**screams into void\**)
